---
# Author: Shubham Setia
# required: cli_region          : The region where the vol is present
# optional: cli_delete          : Pass true if you actually want to delete vols, default value is false

- name: Delete unused vols where tag:Name doesn't start with prefix
  hosts: localhost
  gather_facts: no
  max_fail_percentage: "{{ cli_max_fail_percentage|default(100) }}"
  vars_files:
    - ../vars_files/secrets.yml
  vars:
    cli_delete: false
    slack_domain: slackproxy.p.example.com
    slack_token: "{{ slack_token }}"
    slack_channel: "#test"
  tasks:
  - name: Get list of available/unused vols
    ec2_vol_facts:
      region: "{{ cli_region }}"
      filters:
        status: available
    register: ec2_vol_unused

  - name: Get list of available/unused vols with tag:Name prefix as DND
    ec2_vol_facts:
      region: "{{ cli_region }}"
      filters:
        status: available
        "tag:Name": "DND*"
    register: ec2_vol_info_do_not_delete

  - name: Task block
    block:
      - name: Print vol ids to be deleted
        debug:
          msg: "Ids of vol not having DND in Name tag: {{ ec2_vol_ids_to_be_deleted }}"

      - name: Slack notification
        slack:
          domain: "{{ slack_domain }}"
          token: "{{ slack_token }}"
          msg: |
            AWS ebs vols to be deleted on Tuesday for `{{ cli_region }}` region:
            {% for vol in ec2_vol_tags_to_be_deleted %}
            `{{ vol }}`
            {% endfor %}
          channel: "{{ slack_channel }}"
          validate_certs: yes
        when: ec2_vol_tags_to_be_deleted|length > 0

      - name: Delete unused vols where tag:Name doesn't start with prefix
        ec2_vol:
          region: "{{cli_region}}"
          id: '{{ item }}'
          state: absent
        loop: "{{ ec2_vol_ids_to_be_deleted }}"
        when: cli_delete|bool

      - name: Print vols which haven't got deleted due to prefix
        debug:
          msg: "Ids of vol having DND in Name tag hence haven't got deleted: {{ ec2_dnd_vol_list }}"

    vars:
      # Fetch ec2 unused vol list
      ec2_vol_list: |
        {{ ec2_vol_unused.volumes|map(attribute='id')|list }}
      # Fetch ec2 unused vol tag:Name list
      ec2_vol_tag_name_list: |
        {{ [] if ec2_vol_my_tag_name_unused is string else ec2_vol_my_tag_name_unused }}
      ec2_vol_tag_name_unused: |
        {% for tag_name in ec2_vol_unused.volumes %}
        {% if tag_name.tags.Name is defined %}
        - "{{ tag_name.tags.Name }}: {{ tag_name.id }}"
        {% else %}
        - "{{ tag_name.id }}"
        {% endif %}
        {% endfor %}
      ec2_vol_my_tag_name_unused: |
        {{ ec2_vol_tag_name_unused|from_yaml }}
      # Fetch ec2 unused vol list with DND prefix
      ec2_dnd_vol_list: |
        {{ ec2_vol_info_do_not_delete.volumes|map(attribute='id')|list }}
      # Fetch ec2 unused vol tag:Name list with DND prefix
      ec2_dnd_vol_tag_name_list: |
        {{ [] if ec2_dnd_vol_my_tag_name_unused is string else ec2_dnd_vol_my_tag_name_unused }}
      ec2_dnd_vol_tag_name_unused: |
        {% for tag_name in ec2_vol_info_do_not_delete.volumes %}
        {% if tag_name.tags.Name is defined %}
        - "{{ tag_name.tags.Name }}: {{ tag_name.id }}"
        {% else %}
        - "{{ tag_name.id }}"
        {% endif %}
        {% endfor %}
      ec2_dnd_vol_my_tag_name_unused: |
        {{ ec2_dnd_vol_tag_name_unused|from_yaml }}
      # Fetch ec2 vol ids to be deleted
      ec2_vol_ids_to_be_deleted: |
        {{ ec2_vol_list|difference(ec2_dnd_vol_list) }}
      # Fetch ec2 vol tag:Name to be deleted
      ec2_vol_tags_to_be_deleted: |
        {{ ec2_vol_tag_name_list|difference(ec2_dnd_vol_tag_name_list) }}
